export enum MovementCategory {
  INVESTMENT = 'INVESTMENT',
  FOOD = 'FOOD',
  CARD = 'CARD',
  TRANSPORT = 'TRANSPORT',
  HEALTH = 'HEALTH',
  MONTHLY_EXPENSES = 'MONTHLY_EXPENSES',
  VEHICLES = 'VEHICLES',
  TRIP = 'TRIP'
}