export enum AssetOperationType {
  BUY = 'BUY',
  SELL = 'SELL',
  SPLIT = 'SPLIT',
  CONTRIBUTION = 'CONTRIBUTION',
  PORTABILITY = 'PORTABILITY',
  CREDIT_ENTRY = 'CREDIT_ENTRY',
  DEPOSIT = 'DEPOSIT',
  JAM = 'JAM',
  WITHDRAW = 'WITHDRAW'
}
